exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: mixed-line-ending
        args:
          - --fix=auto
        language_version: python3.8
      - id: requirements-txt-fixer
        language_version: python3.8
      - id: trailing-whitespace
        language_version: python3.8
      - id: end-of-file-fixer
        language_version: python3.8
      - id: check-added-large-files
        args: ["--maxkb=150000"]
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: fix-encoding-pragma
        args: ["--remove"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$
        language_version: python3.8

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        language_version: python3.8
        args: ['--config=.flake8']
        additional_dependencies: [flake8-isort]
